trigger:
  paths:
    include:
      - frontend/ecomproject/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  key: '$(git_key)'
  frontendImageName: 'frontend_image'

pool:
  name: 'agentpool-to-build-container'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: BuildFrontend
    displayName: Build frontend Docker image
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: 'dockerregestryconnection'
    
    - task: Docker@2
      displayName: Build frontend Docker image
      inputs:
        containerRegistry: 'dockerregestryconnection'
        repository: 'tharun9705/movie_recommendation_applications_repository'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/frontend/ecommerce/Dockerfile'
        tags: '$(frontendImageName)$(tag)'

- stage: Push
  displayName: Push
  jobs:
  - job: PushFrontend
    displayName: Push frontend Docker image
    steps:
    - task: Docker@2
      displayName: Push Docker image
      inputs:
        containerRegistry: 'dockerregestryconnection'
        repository: 'tharun9705/movie_recommendation_applications_repository'
        command: 'push'
        tags: '$(frontendImageName)$(tag)'

- stage: UpdateK8sFile
  displayName: Update k8s file
  jobs:
  - job: UpdateK8s
    displayName: Update k8s file with new Docker ID
    steps:
    - task: ShellScript@2
      displayName: Update Kubernetes Configuration
      inputs:
        scriptPath: '$(Build.SourcesDirectory)/code_files_to_update_k8s/update_frontend_id.sh'
        args: '$(frontendImageName)$(tag) $(key)'
